modLoader="kotlinforforge"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/octarine-noise/BetterFoliage/issues"
license="MIT"
[[mods]]
    modId="betterfoliage"
    version="${version}"
    displayName="Better Foliage"
    authors="octarine-noise"
    description='''
Leafier leaves and grassier grass.
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/better-foliage"
    side="CLIENT"